/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum WeaponCombatStyle {
    ACCURATE = 'accurate',
    AIM_AND_FIRE = 'aim and fire',
    BASH = 'bash',
    BLAZE = 'blaze',
    BLOCK = 'block',
    CHOP = 'chop',
    DEFLECT = 'deflect',
    FEND = 'fend',
    FLARE = 'flare',
    FLICK = 'flick',
    FOCUS = 'focus',
    HACK = 'hack',
    IMPALE = 'impale',
    JAB = 'jab',
    KICK = 'kick',
    LASH = 'lash',
    LONG_FUSE = 'long fuse',
    LONGRANGE = 'longrange',
    LUNGE = 'lunge',
    MEDIUM_FUSE = 'medium fuse',
    POUND = 'pound',
    PUMMEL = 'pummel',
    PUNCH = 'punch',
    RAPID = 'rapid',
    REAP = 'reap',
    SCORCH = 'scorch',
    SHORT_FUSE = 'short fuse',
    SLASH = 'slash',
    SMASH = 'smash',
    SPELL = 'spell',
    SPELL_DEFENSIVE_ = 'spell (defensive)',
    SPIKE = 'spike',
    STAB = 'stab',
    SWIPE = 'swipe',
}